
namespace Computer_Managment_System
{
    partial class ServiceRepair_StatusEdit
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ServiceRepair_StatusEdit));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.label5 = new System.Windows.Forms.Label();
            this.txt_ServiceID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txt_ServiceName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ServiceType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txt_ServiceOwner = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txt_Duration = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.txt_SearchAddnewrepair = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dvg_EditServiceStatus = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btn_addStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_deleteStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_clearStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_updateStatus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lbl_close = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dvg_EditServiceStatus)).BeginInit();
            this.SuspendLayout();
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 10.25F, System.Drawing.FontStyle.Bold);
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(43, 114);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(69, 19);
            this.label5.TabIndex = 5;
            this.label5.Text = "ServiceID";
            // 
            // txt_ServiceID
            // 
            this.txt_ServiceID.AcceptsReturn = false;
            this.txt_ServiceID.AcceptsTab = false;
            this.txt_ServiceID.AnimationSpeed = 200;
            this.txt_ServiceID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ServiceID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ServiceID.AutoSizeHeight = true;
            this.txt_ServiceID.BackColor = System.Drawing.Color.Transparent;
            this.txt_ServiceID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ServiceID.BackgroundImage")));
            this.txt_ServiceID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ServiceID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ServiceID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ServiceID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ServiceID.BorderRadius = 1;
            this.txt_ServiceID.BorderThickness = 1;
            this.txt_ServiceID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ServiceID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ServiceID.DefaultText = "";
            this.txt_ServiceID.FillColor = System.Drawing.Color.White;
            this.txt_ServiceID.HideSelection = true;
            this.txt_ServiceID.IconLeft = null;
            this.txt_ServiceID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceID.IconPadding = 10;
            this.txt_ServiceID.IconRight = null;
            this.txt_ServiceID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceID.Lines = new string[0];
            this.txt_ServiceID.Location = new System.Drawing.Point(151, 103);
            this.txt_ServiceID.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceID.MaxLength = 32767;
            this.txt_ServiceID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ServiceID.Modified = false;
            this.txt_ServiceID.Multiline = false;
            this.txt_ServiceID.Name = "txt_ServiceID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ServiceID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceID.OnIdleState = stateProperties4;
            this.txt_ServiceID.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceID.PasswordChar = '\0';
            this.txt_ServiceID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ServiceID.PlaceholderText = "Auto Generation";
            this.txt_ServiceID.ReadOnly = true;
            this.txt_ServiceID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ServiceID.SelectedText = "";
            this.txt_ServiceID.SelectionLength = 0;
            this.txt_ServiceID.SelectionStart = 0;
            this.txt_ServiceID.ShortcutsEnabled = true;
            this.txt_ServiceID.Size = new System.Drawing.Size(316, 35);
            this.txt_ServiceID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ServiceID.TabIndex = 6;
            this.txt_ServiceID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ServiceID.TextMarginBottom = 0;
            this.txt_ServiceID.TextMarginLeft = 3;
            this.txt_ServiceID.TextMarginTop = 1;
            this.txt_ServiceID.TextPlaceholder = "Auto Generation";
            this.txt_ServiceID.UseSystemPasswordChar = false;
            this.txt_ServiceID.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 10.25F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(42, 170);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(96, 19);
            this.label1.TabIndex = 7;
            this.label1.Text = "Service Name";
            // 
            // txt_ServiceName
            // 
            this.txt_ServiceName.AcceptsReturn = false;
            this.txt_ServiceName.AcceptsTab = false;
            this.txt_ServiceName.AnimationSpeed = 200;
            this.txt_ServiceName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ServiceName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ServiceName.AutoSizeHeight = true;
            this.txt_ServiceName.BackColor = System.Drawing.Color.Transparent;
            this.txt_ServiceName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ServiceName.BackgroundImage")));
            this.txt_ServiceName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ServiceName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ServiceName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ServiceName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ServiceName.BorderRadius = 1;
            this.txt_ServiceName.BorderThickness = 1;
            this.txt_ServiceName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ServiceName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ServiceName.DefaultText = "";
            this.txt_ServiceName.FillColor = System.Drawing.Color.White;
            this.txt_ServiceName.HideSelection = true;
            this.txt_ServiceName.IconLeft = null;
            this.txt_ServiceName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceName.IconPadding = 10;
            this.txt_ServiceName.IconRight = null;
            this.txt_ServiceName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceName.Lines = new string[0];
            this.txt_ServiceName.Location = new System.Drawing.Point(150, 158);
            this.txt_ServiceName.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceName.MaxLength = 32767;
            this.txt_ServiceName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ServiceName.Modified = false;
            this.txt_ServiceName.Multiline = false;
            this.txt_ServiceName.Name = "txt_ServiceName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ServiceName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceName.OnIdleState = stateProperties8;
            this.txt_ServiceName.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceName.PasswordChar = '\0';
            this.txt_ServiceName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ServiceName.PlaceholderText = "Enter Service Name";
            this.txt_ServiceName.ReadOnly = false;
            this.txt_ServiceName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ServiceName.SelectedText = "";
            this.txt_ServiceName.SelectionLength = 0;
            this.txt_ServiceName.SelectionStart = 0;
            this.txt_ServiceName.ShortcutsEnabled = true;
            this.txt_ServiceName.Size = new System.Drawing.Size(316, 35);
            this.txt_ServiceName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ServiceName.TabIndex = 8;
            this.txt_ServiceName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ServiceName.TextMarginBottom = 0;
            this.txt_ServiceName.TextMarginLeft = 3;
            this.txt_ServiceName.TextMarginTop = 1;
            this.txt_ServiceName.TextPlaceholder = "Enter Service Name";
            this.txt_ServiceName.UseSystemPasswordChar = false;
            this.txt_ServiceName.WordWrap = true;
            // 
            // txt_ServiceType
            // 
            this.txt_ServiceType.AcceptsReturn = false;
            this.txt_ServiceType.AcceptsTab = false;
            this.txt_ServiceType.AnimationSpeed = 200;
            this.txt_ServiceType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ServiceType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ServiceType.AutoSizeHeight = true;
            this.txt_ServiceType.BackColor = System.Drawing.Color.Transparent;
            this.txt_ServiceType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ServiceType.BackgroundImage")));
            this.txt_ServiceType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ServiceType.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ServiceType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ServiceType.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ServiceType.BorderRadius = 1;
            this.txt_ServiceType.BorderThickness = 1;
            this.txt_ServiceType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ServiceType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceType.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ServiceType.DefaultText = "";
            this.txt_ServiceType.FillColor = System.Drawing.Color.White;
            this.txt_ServiceType.HideSelection = true;
            this.txt_ServiceType.IconLeft = null;
            this.txt_ServiceType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceType.IconPadding = 10;
            this.txt_ServiceType.IconRight = null;
            this.txt_ServiceType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceType.Lines = new string[0];
            this.txt_ServiceType.Location = new System.Drawing.Point(150, 222);
            this.txt_ServiceType.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceType.MaxLength = 32767;
            this.txt_ServiceType.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ServiceType.Modified = false;
            this.txt_ServiceType.Multiline = false;
            this.txt_ServiceType.Name = "txt_ServiceType";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceType.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ServiceType.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceType.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceType.OnIdleState = stateProperties12;
            this.txt_ServiceType.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceType.PasswordChar = '\0';
            this.txt_ServiceType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ServiceType.PlaceholderText = "On / Off";
            this.txt_ServiceType.ReadOnly = false;
            this.txt_ServiceType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ServiceType.SelectedText = "";
            this.txt_ServiceType.SelectionLength = 0;
            this.txt_ServiceType.SelectionStart = 0;
            this.txt_ServiceType.ShortcutsEnabled = true;
            this.txt_ServiceType.Size = new System.Drawing.Size(316, 35);
            this.txt_ServiceType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ServiceType.TabIndex = 8;
            this.txt_ServiceType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ServiceType.TextMarginBottom = 0;
            this.txt_ServiceType.TextMarginLeft = 3;
            this.txt_ServiceType.TextMarginTop = 1;
            this.txt_ServiceType.TextPlaceholder = "On / Off";
            this.txt_ServiceType.UseSystemPasswordChar = false;
            this.txt_ServiceType.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.25F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(43, 222);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(98, 19);
            this.label2.TabIndex = 7;
            this.label2.Text = "Service Status";
            // 
            // txt_ServiceOwner
            // 
            this.txt_ServiceOwner.AcceptsReturn = false;
            this.txt_ServiceOwner.AcceptsTab = false;
            this.txt_ServiceOwner.AnimationSpeed = 200;
            this.txt_ServiceOwner.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ServiceOwner.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ServiceOwner.AutoSizeHeight = true;
            this.txt_ServiceOwner.BackColor = System.Drawing.Color.Transparent;
            this.txt_ServiceOwner.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ServiceOwner.BackgroundImage")));
            this.txt_ServiceOwner.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ServiceOwner.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ServiceOwner.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ServiceOwner.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ServiceOwner.BorderRadius = 1;
            this.txt_ServiceOwner.BorderThickness = 1;
            this.txt_ServiceOwner.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ServiceOwner.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceOwner.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ServiceOwner.DefaultText = "";
            this.txt_ServiceOwner.FillColor = System.Drawing.Color.White;
            this.txt_ServiceOwner.HideSelection = true;
            this.txt_ServiceOwner.IconLeft = null;
            this.txt_ServiceOwner.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceOwner.IconPadding = 10;
            this.txt_ServiceOwner.IconRight = null;
            this.txt_ServiceOwner.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ServiceOwner.Lines = new string[0];
            this.txt_ServiceOwner.Location = new System.Drawing.Point(635, 103);
            this.txt_ServiceOwner.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceOwner.MaxLength = 32767;
            this.txt_ServiceOwner.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ServiceOwner.Modified = false;
            this.txt_ServiceOwner.Multiline = false;
            this.txt_ServiceOwner.Name = "txt_ServiceOwner";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceOwner.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ServiceOwner.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceOwner.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ServiceOwner.OnIdleState = stateProperties16;
            this.txt_ServiceOwner.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ServiceOwner.PasswordChar = '\0';
            this.txt_ServiceOwner.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ServiceOwner.PlaceholderText = "Mr / Ms . Name";
            this.txt_ServiceOwner.ReadOnly = false;
            this.txt_ServiceOwner.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ServiceOwner.SelectedText = "";
            this.txt_ServiceOwner.SelectionLength = 0;
            this.txt_ServiceOwner.SelectionStart = 0;
            this.txt_ServiceOwner.ShortcutsEnabled = true;
            this.txt_ServiceOwner.Size = new System.Drawing.Size(336, 35);
            this.txt_ServiceOwner.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ServiceOwner.TabIndex = 8;
            this.txt_ServiceOwner.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ServiceOwner.TextMarginBottom = 0;
            this.txt_ServiceOwner.TextMarginLeft = 3;
            this.txt_ServiceOwner.TextMarginTop = 1;
            this.txt_ServiceOwner.TextPlaceholder = "Mr / Ms . Name";
            this.txt_ServiceOwner.UseSystemPasswordChar = false;
            this.txt_ServiceOwner.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI Semibold", 10.25F, System.Drawing.FontStyle.Bold);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(513, 114);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(117, 19);
            this.label6.TabIndex = 7;
            this.label6.Text = "Technician Name";
            // 
            // txt_Duration
            // 
            this.txt_Duration.AcceptsReturn = false;
            this.txt_Duration.AcceptsTab = false;
            this.txt_Duration.AnimationSpeed = 200;
            this.txt_Duration.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Duration.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Duration.AutoSizeHeight = true;
            this.txt_Duration.BackColor = System.Drawing.Color.Transparent;
            this.txt_Duration.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Duration.BackgroundImage")));
            this.txt_Duration.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Duration.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Duration.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Duration.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Duration.BorderRadius = 1;
            this.txt_Duration.BorderThickness = 1;
            this.txt_Duration.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Duration.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Duration.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Duration.DefaultText = "";
            this.txt_Duration.FillColor = System.Drawing.Color.White;
            this.txt_Duration.HideSelection = true;
            this.txt_Duration.IconLeft = null;
            this.txt_Duration.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Duration.IconPadding = 10;
            this.txt_Duration.IconRight = null;
            this.txt_Duration.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Duration.Lines = new string[0];
            this.txt_Duration.Location = new System.Drawing.Point(635, 160);
            this.txt_Duration.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_Duration.MaxLength = 32767;
            this.txt_Duration.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Duration.Modified = false;
            this.txt_Duration.Multiline = false;
            this.txt_Duration.Name = "txt_Duration";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Duration.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Duration.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Duration.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Duration.OnIdleState = stateProperties20;
            this.txt_Duration.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_Duration.PasswordChar = '\0';
            this.txt_Duration.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Duration.PlaceholderText = "eg - 1 week , 2week";
            this.txt_Duration.ReadOnly = false;
            this.txt_Duration.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Duration.SelectedText = "";
            this.txt_Duration.SelectionLength = 0;
            this.txt_Duration.SelectionStart = 0;
            this.txt_Duration.ShortcutsEnabled = true;
            this.txt_Duration.Size = new System.Drawing.Size(336, 35);
            this.txt_Duration.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Duration.TabIndex = 8;
            this.txt_Duration.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Duration.TextMarginBottom = 0;
            this.txt_Duration.TextMarginLeft = 3;
            this.txt_Duration.TextMarginTop = 1;
            this.txt_Duration.TextPlaceholder = "eg - 1 week , 2week";
            this.txt_Duration.UseSystemPasswordChar = false;
            this.txt_Duration.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI Semibold", 10.25F, System.Drawing.FontStyle.Bold);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(515, 170);
            this.label7.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(68, 19);
            this.label7.TabIndex = 7;
            this.label7.Text = "Duration ";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 17F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(396, 39);
            this.label9.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(220, 29);
            this.label9.TabIndex = 9;
            this.label9.Text = "Edit Service Status ";
            // 
            // txt_SearchAddnewrepair
            // 
            this.txt_SearchAddnewrepair.AcceptsReturn = false;
            this.txt_SearchAddnewrepair.AcceptsTab = false;
            this.txt_SearchAddnewrepair.AnimationSpeed = 200;
            this.txt_SearchAddnewrepair.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SearchAddnewrepair.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SearchAddnewrepair.AutoSizeHeight = true;
            this.txt_SearchAddnewrepair.BackColor = System.Drawing.Color.Transparent;
            this.txt_SearchAddnewrepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SearchAddnewrepair.BackgroundImage")));
            this.txt_SearchAddnewrepair.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SearchAddnewrepair.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_SearchAddnewrepair.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SearchAddnewrepair.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SearchAddnewrepair.BorderRadius = 25;
            this.txt_SearchAddnewrepair.BorderThickness = 1;
            this.txt_SearchAddnewrepair.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SearchAddnewrepair.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_SearchAddnewrepair.DefaultText = "";
            this.txt_SearchAddnewrepair.FillColor = System.Drawing.Color.White;
            this.txt_SearchAddnewrepair.HideSelection = true;
            this.txt_SearchAddnewrepair.IconLeft = null;
            this.txt_SearchAddnewrepair.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.IconPadding = 10;
            this.txt_SearchAddnewrepair.IconRight = null;
            this.txt_SearchAddnewrepair.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.Lines = new string[0];
            this.txt_SearchAddnewrepair.Location = new System.Drawing.Point(44, 277);
            this.txt_SearchAddnewrepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_SearchAddnewrepair.MaxLength = 32767;
            this.txt_SearchAddnewrepair.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_SearchAddnewrepair.Modified = false;
            this.txt_SearchAddnewrepair.Multiline = false;
            this.txt_SearchAddnewrepair.Name = "txt_SearchAddnewrepair";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_SearchAddnewrepair.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnIdleState = stateProperties24;
            this.txt_SearchAddnewrepair.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_SearchAddnewrepair.PasswordChar = '\0';
            this.txt_SearchAddnewrepair.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txt_SearchAddnewrepair.PlaceholderText = "Search";
            this.txt_SearchAddnewrepair.ReadOnly = false;
            this.txt_SearchAddnewrepair.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SearchAddnewrepair.SelectedText = "";
            this.txt_SearchAddnewrepair.SelectionLength = 0;
            this.txt_SearchAddnewrepair.SelectionStart = 0;
            this.txt_SearchAddnewrepair.ShortcutsEnabled = true;
            this.txt_SearchAddnewrepair.Size = new System.Drawing.Size(424, 35);
            this.txt_SearchAddnewrepair.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_SearchAddnewrepair.TabIndex = 11;
            this.txt_SearchAddnewrepair.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SearchAddnewrepair.TextMarginBottom = 0;
            this.txt_SearchAddnewrepair.TextMarginLeft = 3;
            this.txt_SearchAddnewrepair.TextMarginTop = 1;
            this.txt_SearchAddnewrepair.TextPlaceholder = "Search";
            this.txt_SearchAddnewrepair.UseSystemPasswordChar = false;
            this.txt_SearchAddnewrepair.WordWrap = true;
            this.txt_SearchAddnewrepair.TextChanged += new System.EventHandler(this.txt_SearchAddnewrepair_TextChanged);
            // 
            // dvg_EditServiceStatus
            // 
            this.dvg_EditServiceStatus.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dvg_EditServiceStatus.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dvg_EditServiceStatus.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dvg_EditServiceStatus.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dvg_EditServiceStatus.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dvg_EditServiceStatus.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dvg_EditServiceStatus.ColumnHeadersHeight = 40;
            this.dvg_EditServiceStatus.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.dvg_EditServiceStatus.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dvg_EditServiceStatus.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dvg_EditServiceStatus.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.dvg_EditServiceStatus.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_EditServiceStatus.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dvg_EditServiceStatus.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_EditServiceStatus.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dvg_EditServiceStatus.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.dvg_EditServiceStatus.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.CurrentTheme.Name = null;
            this.dvg_EditServiceStatus.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.dvg_EditServiceStatus.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dvg_EditServiceStatus.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dvg_EditServiceStatus.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dvg_EditServiceStatus.DefaultCellStyle = dataGridViewCellStyle3;
            this.dvg_EditServiceStatus.EnableHeadersVisualStyles = false;
            this.dvg_EditServiceStatus.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dvg_EditServiceStatus.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_EditServiceStatus.HeaderBgColor = System.Drawing.Color.Empty;
            this.dvg_EditServiceStatus.HeaderForeColor = System.Drawing.Color.White;
            this.dvg_EditServiceStatus.Location = new System.Drawing.Point(45, 335);
            this.dvg_EditServiceStatus.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dvg_EditServiceStatus.Name = "dvg_EditServiceStatus";
            this.dvg_EditServiceStatus.RowHeadersVisible = false;
            this.dvg_EditServiceStatus.RowHeadersWidth = 51;
            this.dvg_EditServiceStatus.RowTemplate.Height = 40;
            this.dvg_EditServiceStatus.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dvg_EditServiceStatus.Size = new System.Drawing.Size(926, 249);
            this.dvg_EditServiceStatus.TabIndex = 16;
            this.dvg_EditServiceStatus.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            this.dvg_EditServiceStatus.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dvg_EditServiceStatus_CellClick);
            // 
            // btn_addStatus
            // 
            this.btn_addStatus.AllowAnimations = true;
            this.btn_addStatus.AllowMouseEffects = true;
            this.btn_addStatus.AllowToggling = false;
            this.btn_addStatus.AnimationSpeed = 200;
            this.btn_addStatus.AutoGenerateColors = false;
            this.btn_addStatus.AutoRoundBorders = false;
            this.btn_addStatus.AutoSizeLeftIcon = true;
            this.btn_addStatus.AutoSizeRightIcon = true;
            this.btn_addStatus.BackColor = System.Drawing.Color.Transparent;
            this.btn_addStatus.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_addStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_addStatus.BackgroundImage")));
            this.btn_addStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addStatus.ButtonText = "Add";
            this.btn_addStatus.ButtonTextMarginLeft = 0;
            this.btn_addStatus.ColorContrastOnClick = 45;
            this.btn_addStatus.ColorContrastOnHover = 45;
            this.btn_addStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_addStatus.CustomizableEdges = borderEdges1;
            this.btn_addStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_addStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_addStatus.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_addStatus.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_addStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_addStatus.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_addStatus.ForeColor = System.Drawing.Color.White;
            this.btn_addStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_addStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_addStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_addStatus.IconMarginLeft = 11;
            this.btn_addStatus.IconPadding = 10;
            this.btn_addStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_addStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_addStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_addStatus.IconSize = 25;
            this.btn_addStatus.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_addStatus.IdleBorderRadius = 30;
            this.btn_addStatus.IdleBorderThickness = 1;
            this.btn_addStatus.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_addStatus.IdleIconLeftImage = null;
            this.btn_addStatus.IdleIconRightImage = null;
            this.btn_addStatus.IndicateFocus = false;
            this.btn_addStatus.Location = new System.Drawing.Point(635, 222);
            this.btn_addStatus.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_addStatus.Name = "btn_addStatus";
            this.btn_addStatus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_addStatus.OnDisabledState.BorderRadius = 30;
            this.btn_addStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addStatus.OnDisabledState.BorderThickness = 1;
            this.btn_addStatus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_addStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_addStatus.OnDisabledState.IconLeftImage = null;
            this.btn_addStatus.OnDisabledState.IconRightImage = null;
            this.btn_addStatus.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_addStatus.onHoverState.BorderRadius = 30;
            this.btn_addStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addStatus.onHoverState.BorderThickness = 1;
            this.btn_addStatus.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_addStatus.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_addStatus.onHoverState.IconLeftImage = null;
            this.btn_addStatus.onHoverState.IconRightImage = null;
            this.btn_addStatus.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_addStatus.OnIdleState.BorderRadius = 30;
            this.btn_addStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addStatus.OnIdleState.BorderThickness = 1;
            this.btn_addStatus.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_addStatus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_addStatus.OnIdleState.IconLeftImage = null;
            this.btn_addStatus.OnIdleState.IconRightImage = null;
            this.btn_addStatus.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_addStatus.OnPressedState.BorderRadius = 30;
            this.btn_addStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addStatus.OnPressedState.BorderThickness = 1;
            this.btn_addStatus.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_addStatus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_addStatus.OnPressedState.IconLeftImage = null;
            this.btn_addStatus.OnPressedState.IconRightImage = null;
            this.btn_addStatus.Size = new System.Drawing.Size(98, 32);
            this.btn_addStatus.TabIndex = 17;
            this.btn_addStatus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_addStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_addStatus.TextMarginLeft = 0;
            this.btn_addStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_addStatus.UseDefaultRadiusAndThickness = true;
            this.btn_addStatus.Click += new System.EventHandler(this.btn_addStatus_Click);
            // 
            // btn_deleteStatus
            // 
            this.btn_deleteStatus.AllowAnimations = true;
            this.btn_deleteStatus.AllowMouseEffects = true;
            this.btn_deleteStatus.AllowToggling = false;
            this.btn_deleteStatus.AnimationSpeed = 200;
            this.btn_deleteStatus.AutoGenerateColors = false;
            this.btn_deleteStatus.AutoRoundBorders = false;
            this.btn_deleteStatus.AutoSizeLeftIcon = true;
            this.btn_deleteStatus.AutoSizeRightIcon = true;
            this.btn_deleteStatus.BackColor = System.Drawing.Color.Transparent;
            this.btn_deleteStatus.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_deleteStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_deleteStatus.BackgroundImage")));
            this.btn_deleteStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteStatus.ButtonText = "Delete";
            this.btn_deleteStatus.ButtonTextMarginLeft = 0;
            this.btn_deleteStatus.ColorContrastOnClick = 45;
            this.btn_deleteStatus.ColorContrastOnHover = 45;
            this.btn_deleteStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_deleteStatus.CustomizableEdges = borderEdges2;
            this.btn_deleteStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_deleteStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_deleteStatus.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_deleteStatus.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_deleteStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_deleteStatus.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_deleteStatus.ForeColor = System.Drawing.Color.White;
            this.btn_deleteStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_deleteStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_deleteStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_deleteStatus.IconMarginLeft = 11;
            this.btn_deleteStatus.IconPadding = 10;
            this.btn_deleteStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_deleteStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_deleteStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_deleteStatus.IconSize = 25;
            this.btn_deleteStatus.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteStatus.IdleBorderRadius = 30;
            this.btn_deleteStatus.IdleBorderThickness = 1;
            this.btn_deleteStatus.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteStatus.IdleIconLeftImage = null;
            this.btn_deleteStatus.IdleIconRightImage = null;
            this.btn_deleteStatus.IndicateFocus = false;
            this.btn_deleteStatus.Location = new System.Drawing.Point(869, 222);
            this.btn_deleteStatus.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_deleteStatus.Name = "btn_deleteStatus";
            this.btn_deleteStatus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_deleteStatus.OnDisabledState.BorderRadius = 30;
            this.btn_deleteStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteStatus.OnDisabledState.BorderThickness = 1;
            this.btn_deleteStatus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_deleteStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_deleteStatus.OnDisabledState.IconLeftImage = null;
            this.btn_deleteStatus.OnDisabledState.IconRightImage = null;
            this.btn_deleteStatus.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_deleteStatus.onHoverState.BorderRadius = 30;
            this.btn_deleteStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteStatus.onHoverState.BorderThickness = 1;
            this.btn_deleteStatus.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_deleteStatus.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteStatus.onHoverState.IconLeftImage = null;
            this.btn_deleteStatus.onHoverState.IconRightImage = null;
            this.btn_deleteStatus.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteStatus.OnIdleState.BorderRadius = 30;
            this.btn_deleteStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteStatus.OnIdleState.BorderThickness = 1;
            this.btn_deleteStatus.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteStatus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteStatus.OnIdleState.IconLeftImage = null;
            this.btn_deleteStatus.OnIdleState.IconRightImage = null;
            this.btn_deleteStatus.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_deleteStatus.OnPressedState.BorderRadius = 30;
            this.btn_deleteStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteStatus.OnPressedState.BorderThickness = 1;
            this.btn_deleteStatus.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_deleteStatus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteStatus.OnPressedState.IconLeftImage = null;
            this.btn_deleteStatus.OnPressedState.IconRightImage = null;
            this.btn_deleteStatus.Size = new System.Drawing.Size(102, 32);
            this.btn_deleteStatus.TabIndex = 18;
            this.btn_deleteStatus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_deleteStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_deleteStatus.TextMarginLeft = 0;
            this.btn_deleteStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_deleteStatus.UseDefaultRadiusAndThickness = true;
            this.btn_deleteStatus.Click += new System.EventHandler(this.btn_deleteStatus_Click);
            // 
            // btn_clearStatus
            // 
            this.btn_clearStatus.AllowAnimations = true;
            this.btn_clearStatus.AllowMouseEffects = true;
            this.btn_clearStatus.AllowToggling = false;
            this.btn_clearStatus.AnimationSpeed = 200;
            this.btn_clearStatus.AutoGenerateColors = false;
            this.btn_clearStatus.AutoRoundBorders = false;
            this.btn_clearStatus.AutoSizeLeftIcon = true;
            this.btn_clearStatus.AutoSizeRightIcon = true;
            this.btn_clearStatus.BackColor = System.Drawing.Color.Transparent;
            this.btn_clearStatus.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_clearStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_clearStatus.BackgroundImage")));
            this.btn_clearStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearStatus.ButtonText = "Clear";
            this.btn_clearStatus.ButtonTextMarginLeft = 0;
            this.btn_clearStatus.ColorContrastOnClick = 45;
            this.btn_clearStatus.ColorContrastOnHover = 45;
            this.btn_clearStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_clearStatus.CustomizableEdges = borderEdges3;
            this.btn_clearStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_clearStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_clearStatus.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_clearStatus.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_clearStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_clearStatus.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_clearStatus.ForeColor = System.Drawing.Color.White;
            this.btn_clearStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_clearStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_clearStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_clearStatus.IconMarginLeft = 11;
            this.btn_clearStatus.IconPadding = 10;
            this.btn_clearStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_clearStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_clearStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_clearStatus.IconSize = 25;
            this.btn_clearStatus.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearStatus.IdleBorderRadius = 30;
            this.btn_clearStatus.IdleBorderThickness = 1;
            this.btn_clearStatus.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearStatus.IdleIconLeftImage = null;
            this.btn_clearStatus.IdleIconRightImage = null;
            this.btn_clearStatus.IndicateFocus = false;
            this.btn_clearStatus.Location = new System.Drawing.Point(635, 277);
            this.btn_clearStatus.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_clearStatus.Name = "btn_clearStatus";
            this.btn_clearStatus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_clearStatus.OnDisabledState.BorderRadius = 30;
            this.btn_clearStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearStatus.OnDisabledState.BorderThickness = 1;
            this.btn_clearStatus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_clearStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_clearStatus.OnDisabledState.IconLeftImage = null;
            this.btn_clearStatus.OnDisabledState.IconRightImage = null;
            this.btn_clearStatus.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_clearStatus.onHoverState.BorderRadius = 30;
            this.btn_clearStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearStatus.onHoverState.BorderThickness = 1;
            this.btn_clearStatus.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_clearStatus.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_clearStatus.onHoverState.IconLeftImage = null;
            this.btn_clearStatus.onHoverState.IconRightImage = null;
            this.btn_clearStatus.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearStatus.OnIdleState.BorderRadius = 30;
            this.btn_clearStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearStatus.OnIdleState.BorderThickness = 1;
            this.btn_clearStatus.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearStatus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_clearStatus.OnIdleState.IconLeftImage = null;
            this.btn_clearStatus.OnIdleState.IconRightImage = null;
            this.btn_clearStatus.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_clearStatus.OnPressedState.BorderRadius = 30;
            this.btn_clearStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearStatus.OnPressedState.BorderThickness = 1;
            this.btn_clearStatus.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_clearStatus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_clearStatus.OnPressedState.IconLeftImage = null;
            this.btn_clearStatus.OnPressedState.IconRightImage = null;
            this.btn_clearStatus.Size = new System.Drawing.Size(336, 32);
            this.btn_clearStatus.TabIndex = 19;
            this.btn_clearStatus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_clearStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_clearStatus.TextMarginLeft = 0;
            this.btn_clearStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_clearStatus.UseDefaultRadiusAndThickness = true;
            this.btn_clearStatus.Click += new System.EventHandler(this.btn_clearStatus_Click);
            // 
            // btn_updateStatus
            // 
            this.btn_updateStatus.AllowAnimations = true;
            this.btn_updateStatus.AllowMouseEffects = true;
            this.btn_updateStatus.AllowToggling = false;
            this.btn_updateStatus.AnimationSpeed = 200;
            this.btn_updateStatus.AutoGenerateColors = false;
            this.btn_updateStatus.AutoRoundBorders = false;
            this.btn_updateStatus.AutoSizeLeftIcon = true;
            this.btn_updateStatus.AutoSizeRightIcon = true;
            this.btn_updateStatus.BackColor = System.Drawing.Color.Transparent;
            this.btn_updateStatus.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_updateStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_updateStatus.BackgroundImage")));
            this.btn_updateStatus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateStatus.ButtonText = "Update";
            this.btn_updateStatus.ButtonTextMarginLeft = 0;
            this.btn_updateStatus.ColorContrastOnClick = 45;
            this.btn_updateStatus.ColorContrastOnHover = 45;
            this.btn_updateStatus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_updateStatus.CustomizableEdges = borderEdges4;
            this.btn_updateStatus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_updateStatus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_updateStatus.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_updateStatus.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_updateStatus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_updateStatus.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_updateStatus.ForeColor = System.Drawing.Color.White;
            this.btn_updateStatus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_updateStatus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_updateStatus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_updateStatus.IconMarginLeft = 11;
            this.btn_updateStatus.IconPadding = 10;
            this.btn_updateStatus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_updateStatus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_updateStatus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_updateStatus.IconSize = 25;
            this.btn_updateStatus.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateStatus.IdleBorderRadius = 30;
            this.btn_updateStatus.IdleBorderThickness = 1;
            this.btn_updateStatus.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateStatus.IdleIconLeftImage = null;
            this.btn_updateStatus.IdleIconRightImage = null;
            this.btn_updateStatus.IndicateFocus = false;
            this.btn_updateStatus.Location = new System.Drawing.Point(754, 222);
            this.btn_updateStatus.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_updateStatus.Name = "btn_updateStatus";
            this.btn_updateStatus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_updateStatus.OnDisabledState.BorderRadius = 30;
            this.btn_updateStatus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateStatus.OnDisabledState.BorderThickness = 1;
            this.btn_updateStatus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_updateStatus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_updateStatus.OnDisabledState.IconLeftImage = null;
            this.btn_updateStatus.OnDisabledState.IconRightImage = null;
            this.btn_updateStatus.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_updateStatus.onHoverState.BorderRadius = 30;
            this.btn_updateStatus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateStatus.onHoverState.BorderThickness = 1;
            this.btn_updateStatus.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_updateStatus.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_updateStatus.onHoverState.IconLeftImage = null;
            this.btn_updateStatus.onHoverState.IconRightImage = null;
            this.btn_updateStatus.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateStatus.OnIdleState.BorderRadius = 30;
            this.btn_updateStatus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateStatus.OnIdleState.BorderThickness = 1;
            this.btn_updateStatus.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateStatus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_updateStatus.OnIdleState.IconLeftImage = null;
            this.btn_updateStatus.OnIdleState.IconRightImage = null;
            this.btn_updateStatus.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_updateStatus.OnPressedState.BorderRadius = 30;
            this.btn_updateStatus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateStatus.OnPressedState.BorderThickness = 1;
            this.btn_updateStatus.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_updateStatus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_updateStatus.OnPressedState.IconLeftImage = null;
            this.btn_updateStatus.OnPressedState.IconRightImage = null;
            this.btn_updateStatus.Size = new System.Drawing.Size(98, 32);
            this.btn_updateStatus.TabIndex = 20;
            this.btn_updateStatus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_updateStatus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_updateStatus.TextMarginLeft = 0;
            this.btn_updateStatus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_updateStatus.UseDefaultRadiusAndThickness = true;
            this.btn_updateStatus.Click += new System.EventHandler(this.btn_updateStatus_Click);
            // 
            // lbl_close
            // 
            this.lbl_close.AutoSize = true;
            this.lbl_close.Font = new System.Drawing.Font("Microsoft Sans Serif", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_close.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.lbl_close.Location = new System.Drawing.Point(957, 3);
            this.lbl_close.Name = "lbl_close";
            this.lbl_close.Size = new System.Drawing.Size(43, 42);
            this.lbl_close.TabIndex = 21;
            this.lbl_close.Text = "X";
            this.lbl_close.Click += new System.EventHandler(this.lbl_close_Click);
            // 
            // ServiceRepair_StatusEdit
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(41)))), ((int)(((byte)(53)))));
            this.ClientSize = new System.Drawing.Size(1003, 639);
            this.Controls.Add(this.lbl_close);
            this.Controls.Add(this.btn_updateStatus);
            this.Controls.Add(this.btn_clearStatus);
            this.Controls.Add(this.btn_deleteStatus);
            this.Controls.Add(this.btn_addStatus);
            this.Controls.Add(this.dvg_EditServiceStatus);
            this.Controls.Add(this.txt_SearchAddnewrepair);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txt_Duration);
            this.Controls.Add(this.txt_ServiceOwner);
            this.Controls.Add(this.txt_ServiceType);
            this.Controls.Add(this.txt_ServiceName);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txt_ServiceID);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "ServiceRepair_StatusEdit";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = " ";
            this.Load += new System.EventHandler(this.ServiceRepair_NewRepairEditStatus_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dvg_EditServiceStatus)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ServiceID;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ServiceName;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ServiceType;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ServiceOwner;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Duration;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuTextBox txt_SearchAddnewrepair;
        private Bunifu.UI.WinForms.BunifuDataGridView dvg_EditServiceStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_addStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_deleteStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_clearStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_updateStatus;
        private System.Windows.Forms.Label lbl_close;
    }
}