
namespace Computer_Managment_System
{
    partial class ServiceRepair_NewRepair
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ServiceRepair_NewRepair));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btn_clearRepair = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_deleteRepair = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_updateRepair = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn_addRepair = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.dvg_newrepair = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txt_SearchAddnewrepair = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.txt_TechnicalNote = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ContactNo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ClientAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txt_ClientName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.txt_JobID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.lbl_close = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            this.panel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dvg_newrepair)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(41)))), ((int)(((byte)(53)))));
            this.panel1.Controls.Add(this.panel4);
            this.panel1.Controls.Add(this.btn_clearRepair);
            this.panel1.Controls.Add(this.btn_deleteRepair);
            this.panel1.Controls.Add(this.btn_updateRepair);
            this.panel1.Controls.Add(this.btn_addRepair);
            this.panel1.Controls.Add(this.dvg_newrepair);
            this.panel1.Controls.Add(this.txt_SearchAddnewrepair);
            this.panel1.Controls.Add(this.label8);
            this.panel1.Controls.Add(this.label7);
            this.panel1.Controls.Add(this.txt_TechnicalNote);
            this.panel1.Controls.Add(this.txt_ContactNo);
            this.panel1.Controls.Add(this.txt_ClientAddress);
            this.panel1.Controls.Add(this.label6);
            this.panel1.Controls.Add(this.txt_ClientName);
            this.panel1.Controls.Add(this.label9);
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.txt_JobID);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Location = new System.Drawing.Point(-2, 57);
            this.panel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1056, 535);
            this.panel1.TabIndex = 0;
            // 
            // panel4
            // 
            this.panel4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(50)))), ((int)(((byte)(79)))));
            this.panel4.Controls.Add(this.label13);
            this.panel4.Controls.Add(this.label12);
            this.panel4.Controls.Add(this.label11);
            this.panel4.Controls.Add(this.label10);
            this.panel4.Controls.Add(this.label2);
            this.panel4.Controls.Add(this.bunifuLabel1);
            this.panel4.Location = new System.Drawing.Point(843, 14);
            this.panel4.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(181, 266);
            this.panel4.TabIndex = 11;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.label13.ForeColor = System.Drawing.SystemColors.Control;
            this.label13.Location = new System.Drawing.Point(15, 229);
            this.label13.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(127, 15);
            this.label13.TabIndex = 5;
            this.label13.Text = "05. Hardware Removal";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.label12.ForeColor = System.Drawing.SystemColors.Control;
            this.label12.Location = new System.Drawing.Point(14, 186);
            this.label12.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(103, 15);
            this.label12.TabIndex = 4;
            this.label12.Text = "04. Virus Removal";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.label11.ForeColor = System.Drawing.SystemColors.Control;
            this.label11.Location = new System.Drawing.Point(13, 142);
            this.label11.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(120, 15);
            this.label11.TabIndex = 3;
            this.label11.Text = "03. Network Problem";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.label10.ForeColor = System.Drawing.SystemColors.Control;
            this.label10.Location = new System.Drawing.Point(12, 97);
            this.label10.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(166, 15);
            this.label10.TabIndex = 2;
            this.label10.Text = "02. Windows Update Problem";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.label2.ForeColor = System.Drawing.SystemColors.Control;
            this.label2.Location = new System.Drawing.Point(13, 52);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(115, 15);
            this.label2.TabIndex = 1;
            this.label2.Text = "01. Blue Screen Error";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.Control;
            this.bunifuLabel1.Location = new System.Drawing.Point(8, 11);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(122, 21);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Technical Issues";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btn_clearRepair
            // 
            this.btn_clearRepair.AllowAnimations = true;
            this.btn_clearRepair.AllowMouseEffects = true;
            this.btn_clearRepair.AllowToggling = false;
            this.btn_clearRepair.AnimationSpeed = 200;
            this.btn_clearRepair.AutoGenerateColors = false;
            this.btn_clearRepair.AutoRoundBorders = false;
            this.btn_clearRepair.AutoSizeLeftIcon = true;
            this.btn_clearRepair.AutoSizeRightIcon = true;
            this.btn_clearRepair.BackColor = System.Drawing.Color.Transparent;
            this.btn_clearRepair.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_clearRepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_clearRepair.BackgroundImage")));
            this.btn_clearRepair.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearRepair.ButtonText = "Clear";
            this.btn_clearRepair.ButtonTextMarginLeft = 0;
            this.btn_clearRepair.ColorContrastOnClick = 45;
            this.btn_clearRepair.ColorContrastOnHover = 45;
            this.btn_clearRepair.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_clearRepair.CustomizableEdges = borderEdges5;
            this.btn_clearRepair.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_clearRepair.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_clearRepair.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_clearRepair.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_clearRepair.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_clearRepair.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.btn_clearRepair.ForeColor = System.Drawing.Color.White;
            this.btn_clearRepair.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_clearRepair.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_clearRepair.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_clearRepair.IconMarginLeft = 11;
            this.btn_clearRepair.IconPadding = 10;
            this.btn_clearRepair.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_clearRepair.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_clearRepair.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_clearRepair.IconSize = 25;
            this.btn_clearRepair.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearRepair.IdleBorderRadius = 30;
            this.btn_clearRepair.IdleBorderThickness = 1;
            this.btn_clearRepair.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearRepair.IdleIconLeftImage = null;
            this.btn_clearRepair.IdleIconRightImage = null;
            this.btn_clearRepair.IndicateFocus = false;
            this.btn_clearRepair.Location = new System.Drawing.Point(758, 262);
            this.btn_clearRepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_clearRepair.Name = "btn_clearRepair";
            this.btn_clearRepair.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_clearRepair.OnDisabledState.BorderRadius = 30;
            this.btn_clearRepair.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearRepair.OnDisabledState.BorderThickness = 1;
            this.btn_clearRepair.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_clearRepair.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_clearRepair.OnDisabledState.IconLeftImage = null;
            this.btn_clearRepair.OnDisabledState.IconRightImage = null;
            this.btn_clearRepair.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_clearRepair.onHoverState.BorderRadius = 30;
            this.btn_clearRepair.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearRepair.onHoverState.BorderThickness = 1;
            this.btn_clearRepair.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_clearRepair.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_clearRepair.onHoverState.IconLeftImage = null;
            this.btn_clearRepair.onHoverState.IconRightImage = null;
            this.btn_clearRepair.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearRepair.OnIdleState.BorderRadius = 30;
            this.btn_clearRepair.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearRepair.OnIdleState.BorderThickness = 1;
            this.btn_clearRepair.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_clearRepair.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_clearRepair.OnIdleState.IconLeftImage = null;
            this.btn_clearRepair.OnIdleState.IconRightImage = null;
            this.btn_clearRepair.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_clearRepair.OnPressedState.BorderRadius = 30;
            this.btn_clearRepair.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_clearRepair.OnPressedState.BorderThickness = 1;
            this.btn_clearRepair.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_clearRepair.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_clearRepair.OnPressedState.IconLeftImage = null;
            this.btn_clearRepair.OnPressedState.IconRightImage = null;
            this.btn_clearRepair.Size = new System.Drawing.Size(66, 32);
            this.btn_clearRepair.TabIndex = 10;
            this.btn_clearRepair.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_clearRepair.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_clearRepair.TextMarginLeft = 0;
            this.btn_clearRepair.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_clearRepair.UseDefaultRadiusAndThickness = true;
            this.btn_clearRepair.Click += new System.EventHandler(this.btn_clearRepair_Click);
            // 
            // btn_deleteRepair
            // 
            this.btn_deleteRepair.AllowAnimations = true;
            this.btn_deleteRepair.AllowMouseEffects = true;
            this.btn_deleteRepair.AllowToggling = false;
            this.btn_deleteRepair.AnimationSpeed = 200;
            this.btn_deleteRepair.AutoGenerateColors = false;
            this.btn_deleteRepair.AutoRoundBorders = false;
            this.btn_deleteRepair.AutoSizeLeftIcon = true;
            this.btn_deleteRepair.AutoSizeRightIcon = true;
            this.btn_deleteRepair.BackColor = System.Drawing.Color.Transparent;
            this.btn_deleteRepair.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_deleteRepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_deleteRepair.BackgroundImage")));
            this.btn_deleteRepair.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteRepair.ButtonText = "Delete";
            this.btn_deleteRepair.ButtonTextMarginLeft = 0;
            this.btn_deleteRepair.ColorContrastOnClick = 45;
            this.btn_deleteRepair.ColorContrastOnHover = 45;
            this.btn_deleteRepair.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_deleteRepair.CustomizableEdges = borderEdges6;
            this.btn_deleteRepair.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_deleteRepair.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_deleteRepair.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_deleteRepair.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_deleteRepair.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_deleteRepair.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.btn_deleteRepair.ForeColor = System.Drawing.Color.White;
            this.btn_deleteRepair.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_deleteRepair.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_deleteRepair.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_deleteRepair.IconMarginLeft = 11;
            this.btn_deleteRepair.IconPadding = 10;
            this.btn_deleteRepair.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_deleteRepair.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_deleteRepair.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_deleteRepair.IconSize = 25;
            this.btn_deleteRepair.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteRepair.IdleBorderRadius = 30;
            this.btn_deleteRepair.IdleBorderThickness = 1;
            this.btn_deleteRepair.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteRepair.IdleIconLeftImage = null;
            this.btn_deleteRepair.IdleIconRightImage = null;
            this.btn_deleteRepair.IndicateFocus = false;
            this.btn_deleteRepair.Location = new System.Drawing.Point(646, 262);
            this.btn_deleteRepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_deleteRepair.Name = "btn_deleteRepair";
            this.btn_deleteRepair.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_deleteRepair.OnDisabledState.BorderRadius = 30;
            this.btn_deleteRepair.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteRepair.OnDisabledState.BorderThickness = 1;
            this.btn_deleteRepair.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_deleteRepair.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_deleteRepair.OnDisabledState.IconLeftImage = null;
            this.btn_deleteRepair.OnDisabledState.IconRightImage = null;
            this.btn_deleteRepair.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_deleteRepair.onHoverState.BorderRadius = 30;
            this.btn_deleteRepair.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteRepair.onHoverState.BorderThickness = 1;
            this.btn_deleteRepair.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_deleteRepair.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteRepair.onHoverState.IconLeftImage = null;
            this.btn_deleteRepair.onHoverState.IconRightImage = null;
            this.btn_deleteRepair.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteRepair.OnIdleState.BorderRadius = 30;
            this.btn_deleteRepair.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteRepair.OnIdleState.BorderThickness = 1;
            this.btn_deleteRepair.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_deleteRepair.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteRepair.OnIdleState.IconLeftImage = null;
            this.btn_deleteRepair.OnIdleState.IconRightImage = null;
            this.btn_deleteRepair.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_deleteRepair.OnPressedState.BorderRadius = 30;
            this.btn_deleteRepair.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_deleteRepair.OnPressedState.BorderThickness = 1;
            this.btn_deleteRepair.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_deleteRepair.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_deleteRepair.OnPressedState.IconLeftImage = null;
            this.btn_deleteRepair.OnPressedState.IconRightImage = null;
            this.btn_deleteRepair.Size = new System.Drawing.Size(80, 32);
            this.btn_deleteRepair.TabIndex = 9;
            this.btn_deleteRepair.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_deleteRepair.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_deleteRepair.TextMarginLeft = 0;
            this.btn_deleteRepair.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_deleteRepair.UseDefaultRadiusAndThickness = true;
            this.btn_deleteRepair.Click += new System.EventHandler(this.btn_deleteRepair_Click);
            // 
            // btn_updateRepair
            // 
            this.btn_updateRepair.AllowAnimations = true;
            this.btn_updateRepair.AllowMouseEffects = true;
            this.btn_updateRepair.AllowToggling = false;
            this.btn_updateRepair.AnimationSpeed = 200;
            this.btn_updateRepair.AutoGenerateColors = false;
            this.btn_updateRepair.AutoRoundBorders = false;
            this.btn_updateRepair.AutoSizeLeftIcon = true;
            this.btn_updateRepair.AutoSizeRightIcon = true;
            this.btn_updateRepair.BackColor = System.Drawing.Color.Transparent;
            this.btn_updateRepair.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_updateRepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_updateRepair.BackgroundImage")));
            this.btn_updateRepair.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateRepair.ButtonText = "Update";
            this.btn_updateRepair.ButtonTextMarginLeft = 0;
            this.btn_updateRepair.ColorContrastOnClick = 45;
            this.btn_updateRepair.ColorContrastOnHover = 45;
            this.btn_updateRepair.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_updateRepair.CustomizableEdges = borderEdges7;
            this.btn_updateRepair.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_updateRepair.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_updateRepair.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_updateRepair.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_updateRepair.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_updateRepair.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.btn_updateRepair.ForeColor = System.Drawing.Color.White;
            this.btn_updateRepair.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_updateRepair.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_updateRepair.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_updateRepair.IconMarginLeft = 11;
            this.btn_updateRepair.IconPadding = 10;
            this.btn_updateRepair.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_updateRepair.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_updateRepair.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_updateRepair.IconSize = 25;
            this.btn_updateRepair.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateRepair.IdleBorderRadius = 30;
            this.btn_updateRepair.IdleBorderThickness = 1;
            this.btn_updateRepair.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateRepair.IdleIconLeftImage = null;
            this.btn_updateRepair.IdleIconRightImage = null;
            this.btn_updateRepair.IndicateFocus = false;
            this.btn_updateRepair.Location = new System.Drawing.Point(544, 262);
            this.btn_updateRepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_updateRepair.Name = "btn_updateRepair";
            this.btn_updateRepair.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_updateRepair.OnDisabledState.BorderRadius = 30;
            this.btn_updateRepair.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateRepair.OnDisabledState.BorderThickness = 1;
            this.btn_updateRepair.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_updateRepair.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_updateRepair.OnDisabledState.IconLeftImage = null;
            this.btn_updateRepair.OnDisabledState.IconRightImage = null;
            this.btn_updateRepair.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_updateRepair.onHoverState.BorderRadius = 30;
            this.btn_updateRepair.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateRepair.onHoverState.BorderThickness = 1;
            this.btn_updateRepair.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_updateRepair.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_updateRepair.onHoverState.IconLeftImage = null;
            this.btn_updateRepair.onHoverState.IconRightImage = null;
            this.btn_updateRepair.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateRepair.OnIdleState.BorderRadius = 30;
            this.btn_updateRepair.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateRepair.OnIdleState.BorderThickness = 1;
            this.btn_updateRepair.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_updateRepair.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_updateRepair.OnIdleState.IconLeftImage = null;
            this.btn_updateRepair.OnIdleState.IconRightImage = null;
            this.btn_updateRepair.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_updateRepair.OnPressedState.BorderRadius = 30;
            this.btn_updateRepair.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_updateRepair.OnPressedState.BorderThickness = 1;
            this.btn_updateRepair.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_updateRepair.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_updateRepair.OnPressedState.IconLeftImage = null;
            this.btn_updateRepair.OnPressedState.IconRightImage = null;
            this.btn_updateRepair.Size = new System.Drawing.Size(80, 32);
            this.btn_updateRepair.TabIndex = 8;
            this.btn_updateRepair.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_updateRepair.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_updateRepair.TextMarginLeft = 0;
            this.btn_updateRepair.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_updateRepair.UseDefaultRadiusAndThickness = true;
            this.btn_updateRepair.Click += new System.EventHandler(this.btn_updateRepair_Click);
            // 
            // btn_addRepair
            // 
            this.btn_addRepair.AllowAnimations = true;
            this.btn_addRepair.AllowMouseEffects = true;
            this.btn_addRepair.AllowToggling = false;
            this.btn_addRepair.AnimationSpeed = 200;
            this.btn_addRepair.AutoGenerateColors = false;
            this.btn_addRepair.AutoRoundBorders = false;
            this.btn_addRepair.AutoSizeLeftIcon = true;
            this.btn_addRepair.AutoSizeRightIcon = true;
            this.btn_addRepair.BackColor = System.Drawing.Color.Transparent;
            this.btn_addRepair.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_addRepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_addRepair.BackgroundImage")));
            this.btn_addRepair.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addRepair.ButtonText = "Add";
            this.btn_addRepair.ButtonTextMarginLeft = 0;
            this.btn_addRepair.ColorContrastOnClick = 45;
            this.btn_addRepair.ColorContrastOnHover = 45;
            this.btn_addRepair.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_addRepair.CustomizableEdges = borderEdges8;
            this.btn_addRepair.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_addRepair.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_addRepair.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_addRepair.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_addRepair.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_addRepair.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.btn_addRepair.ForeColor = System.Drawing.Color.White;
            this.btn_addRepair.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_addRepair.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_addRepair.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_addRepair.IconMarginLeft = 11;
            this.btn_addRepair.IconPadding = 10;
            this.btn_addRepair.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_addRepair.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_addRepair.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_addRepair.IconSize = 25;
            this.btn_addRepair.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_addRepair.IdleBorderRadius = 30;
            this.btn_addRepair.IdleBorderThickness = 1;
            this.btn_addRepair.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_addRepair.IdleIconLeftImage = null;
            this.btn_addRepair.IdleIconRightImage = null;
            this.btn_addRepair.IndicateFocus = false;
            this.btn_addRepair.Location = new System.Drawing.Point(442, 262);
            this.btn_addRepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.btn_addRepair.Name = "btn_addRepair";
            this.btn_addRepair.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_addRepair.OnDisabledState.BorderRadius = 30;
            this.btn_addRepair.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addRepair.OnDisabledState.BorderThickness = 1;
            this.btn_addRepair.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_addRepair.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_addRepair.OnDisabledState.IconLeftImage = null;
            this.btn_addRepair.OnDisabledState.IconRightImage = null;
            this.btn_addRepair.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_addRepair.onHoverState.BorderRadius = 30;
            this.btn_addRepair.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addRepair.onHoverState.BorderThickness = 1;
            this.btn_addRepair.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_addRepair.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_addRepair.onHoverState.IconLeftImage = null;
            this.btn_addRepair.onHoverState.IconRightImage = null;
            this.btn_addRepair.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_addRepair.OnIdleState.BorderRadius = 30;
            this.btn_addRepair.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addRepair.OnIdleState.BorderThickness = 1;
            this.btn_addRepair.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_addRepair.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_addRepair.OnIdleState.IconLeftImage = null;
            this.btn_addRepair.OnIdleState.IconRightImage = null;
            this.btn_addRepair.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_addRepair.OnPressedState.BorderRadius = 30;
            this.btn_addRepair.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_addRepair.OnPressedState.BorderThickness = 1;
            this.btn_addRepair.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_addRepair.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_addRepair.OnPressedState.IconLeftImage = null;
            this.btn_addRepair.OnPressedState.IconRightImage = null;
            this.btn_addRepair.Size = new System.Drawing.Size(78, 32);
            this.btn_addRepair.TabIndex = 7;
            this.btn_addRepair.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_addRepair.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_addRepair.TextMarginLeft = 0;
            this.btn_addRepair.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_addRepair.UseDefaultRadiusAndThickness = true;
            this.btn_addRepair.Click += new System.EventHandler(this.btn_addRepair_Click);
            // 
            // dvg_newrepair
            // 
            this.dvg_newrepair.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dvg_newrepair.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dvg_newrepair.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dvg_newrepair.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dvg_newrepair.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dvg_newrepair.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dvg_newrepair.ColumnHeadersHeight = 40;
            this.dvg_newrepair.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.dvg_newrepair.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dvg_newrepair.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dvg_newrepair.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.dvg_newrepair.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_newrepair.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dvg_newrepair.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_newrepair.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dvg_newrepair.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.dvg_newrepair.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.CurrentTheme.Name = null;
            this.dvg_newrepair.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.dvg_newrepair.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dvg_newrepair.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dvg_newrepair.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dvg_newrepair.DefaultCellStyle = dataGridViewCellStyle6;
            this.dvg_newrepair.EnableHeadersVisualStyles = false;
            this.dvg_newrepair.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dvg_newrepair.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dvg_newrepair.HeaderBgColor = System.Drawing.Color.Empty;
            this.dvg_newrepair.HeaderForeColor = System.Drawing.Color.White;
            this.dvg_newrepair.Location = new System.Drawing.Point(43, 314);
            this.dvg_newrepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.dvg_newrepair.Name = "dvg_newrepair";
            this.dvg_newrepair.RowHeadersVisible = false;
            this.dvg_newrepair.RowHeadersWidth = 51;
            this.dvg_newrepair.RowTemplate.Height = 40;
            this.dvg_newrepair.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dvg_newrepair.Size = new System.Drawing.Size(965, 201);
            this.dvg_newrepair.TabIndex = 6;
            this.dvg_newrepair.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            this.dvg_newrepair.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dvg_newrepair_CellClick);
            // 
            // txt_SearchAddnewrepair
            // 
            this.txt_SearchAddnewrepair.AcceptsReturn = false;
            this.txt_SearchAddnewrepair.AcceptsTab = false;
            this.txt_SearchAddnewrepair.AnimationSpeed = 200;
            this.txt_SearchAddnewrepair.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SearchAddnewrepair.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SearchAddnewrepair.AutoSizeHeight = true;
            this.txt_SearchAddnewrepair.BackColor = System.Drawing.Color.Transparent;
            this.txt_SearchAddnewrepair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SearchAddnewrepair.BackgroundImage")));
            this.txt_SearchAddnewrepair.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SearchAddnewrepair.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_SearchAddnewrepair.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SearchAddnewrepair.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SearchAddnewrepair.BorderRadius = 25;
            this.txt_SearchAddnewrepair.BorderThickness = 1;
            this.txt_SearchAddnewrepair.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SearchAddnewrepair.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_SearchAddnewrepair.DefaultText = "";
            this.txt_SearchAddnewrepair.FillColor = System.Drawing.Color.White;
            this.txt_SearchAddnewrepair.HideSelection = true;
            this.txt_SearchAddnewrepair.IconLeft = null;
            this.txt_SearchAddnewrepair.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.IconPadding = 10;
            this.txt_SearchAddnewrepair.IconRight = null;
            this.txt_SearchAddnewrepair.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SearchAddnewrepair.Lines = new string[0];
            this.txt_SearchAddnewrepair.Location = new System.Drawing.Point(43, 262);
            this.txt_SearchAddnewrepair.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_SearchAddnewrepair.MaxLength = 32767;
            this.txt_SearchAddnewrepair.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_SearchAddnewrepair.Modified = false;
            this.txt_SearchAddnewrepair.Multiline = false;
            this.txt_SearchAddnewrepair.Name = "txt_SearchAddnewrepair";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_SearchAddnewrepair.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SearchAddnewrepair.OnIdleState = stateProperties28;
            this.txt_SearchAddnewrepair.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_SearchAddnewrepair.PasswordChar = '\0';
            this.txt_SearchAddnewrepair.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txt_SearchAddnewrepair.PlaceholderText = "Search";
            this.txt_SearchAddnewrepair.ReadOnly = false;
            this.txt_SearchAddnewrepair.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SearchAddnewrepair.SelectedText = "";
            this.txt_SearchAddnewrepair.SelectionLength = 0;
            this.txt_SearchAddnewrepair.SelectionStart = 0;
            this.txt_SearchAddnewrepair.ShortcutsEnabled = true;
            this.txt_SearchAddnewrepair.Size = new System.Drawing.Size(371, 35);
            this.txt_SearchAddnewrepair.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_SearchAddnewrepair.TabIndex = 5;
            this.txt_SearchAddnewrepair.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SearchAddnewrepair.TextMarginBottom = 0;
            this.txt_SearchAddnewrepair.TextMarginLeft = 3;
            this.txt_SearchAddnewrepair.TextMarginTop = 1;
            this.txt_SearchAddnewrepair.TextPlaceholder = "Search";
            this.txt_SearchAddnewrepair.UseSystemPasswordChar = false;
            this.txt_SearchAddnewrepair.WordWrap = true;
            this.txt_SearchAddnewrepair.TextChanged += new System.EventHandler(this.btn_SearchNewRepair_TextChanged);
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.label8.ForeColor = System.Drawing.Color.White;
            this.label8.Location = new System.Drawing.Point(439, 136);
            this.label8.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(103, 19);
            this.label8.TabIndex = 0;
            this.label8.Text = "Technical Note";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.label7.ForeColor = System.Drawing.Color.White;
            this.label7.Location = new System.Drawing.Point(439, 74);
            this.label7.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(81, 19);
            this.label7.TabIndex = 0;
            this.label7.Text = "Contact No";
            // 
            // txt_TechnicalNote
            // 
            this.txt_TechnicalNote.AcceptsReturn = false;
            this.txt_TechnicalNote.AcceptsTab = false;
            this.txt_TechnicalNote.AnimationSpeed = 200;
            this.txt_TechnicalNote.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_TechnicalNote.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_TechnicalNote.AutoSizeHeight = true;
            this.txt_TechnicalNote.BackColor = System.Drawing.Color.Transparent;
            this.txt_TechnicalNote.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_TechnicalNote.BackgroundImage")));
            this.txt_TechnicalNote.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_TechnicalNote.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_TechnicalNote.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_TechnicalNote.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_TechnicalNote.BorderRadius = 1;
            this.txt_TechnicalNote.BorderThickness = 1;
            this.txt_TechnicalNote.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_TechnicalNote.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TechnicalNote.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_TechnicalNote.DefaultText = "";
            this.txt_TechnicalNote.FillColor = System.Drawing.Color.White;
            this.txt_TechnicalNote.HideSelection = true;
            this.txt_TechnicalNote.IconLeft = null;
            this.txt_TechnicalNote.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TechnicalNote.IconPadding = 10;
            this.txt_TechnicalNote.IconRight = null;
            this.txt_TechnicalNote.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_TechnicalNote.Lines = new string[0];
            this.txt_TechnicalNote.Location = new System.Drawing.Point(560, 129);
            this.txt_TechnicalNote.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_TechnicalNote.MaxLength = 32767;
            this.txt_TechnicalNote.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_TechnicalNote.Modified = false;
            this.txt_TechnicalNote.Multiline = true;
            this.txt_TechnicalNote.Name = "txt_TechnicalNote";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TechnicalNote.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_TechnicalNote.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TechnicalNote.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_TechnicalNote.OnIdleState = stateProperties32;
            this.txt_TechnicalNote.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_TechnicalNote.PasswordChar = '\0';
            this.txt_TechnicalNote.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_TechnicalNote.PlaceholderText = "Issue that need to fixed";
            this.txt_TechnicalNote.ReadOnly = false;
            this.txt_TechnicalNote.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_TechnicalNote.SelectedText = "";
            this.txt_TechnicalNote.SelectionLength = 0;
            this.txt_TechnicalNote.SelectionStart = 0;
            this.txt_TechnicalNote.ShortcutsEnabled = true;
            this.txt_TechnicalNote.Size = new System.Drawing.Size(263, 102);
            this.txt_TechnicalNote.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_TechnicalNote.TabIndex = 1;
            this.txt_TechnicalNote.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_TechnicalNote.TextMarginBottom = 0;
            this.txt_TechnicalNote.TextMarginLeft = 3;
            this.txt_TechnicalNote.TextMarginTop = 1;
            this.txt_TechnicalNote.TextPlaceholder = "Issue that need to fixed";
            this.txt_TechnicalNote.UseSystemPasswordChar = false;
            this.txt_TechnicalNote.WordWrap = true;
            // 
            // txt_ContactNo
            // 
            this.txt_ContactNo.AcceptsReturn = false;
            this.txt_ContactNo.AcceptsTab = false;
            this.txt_ContactNo.AnimationSpeed = 200;
            this.txt_ContactNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ContactNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ContactNo.AutoSizeHeight = true;
            this.txt_ContactNo.BackColor = System.Drawing.Color.Transparent;
            this.txt_ContactNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ContactNo.BackgroundImage")));
            this.txt_ContactNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ContactNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ContactNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ContactNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ContactNo.BorderRadius = 1;
            this.txt_ContactNo.BorderThickness = 1;
            this.txt_ContactNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ContactNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ContactNo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ContactNo.DefaultText = "";
            this.txt_ContactNo.FillColor = System.Drawing.Color.White;
            this.txt_ContactNo.HideSelection = true;
            this.txt_ContactNo.IconLeft = null;
            this.txt_ContactNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ContactNo.IconPadding = 10;
            this.txt_ContactNo.IconRight = null;
            this.txt_ContactNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ContactNo.Lines = new string[0];
            this.txt_ContactNo.Location = new System.Drawing.Point(560, 64);
            this.txt_ContactNo.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ContactNo.MaxLength = 32767;
            this.txt_ContactNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ContactNo.Modified = false;
            this.txt_ContactNo.Multiline = false;
            this.txt_ContactNo.Name = "txt_ContactNo";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ContactNo.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ContactNo.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ContactNo.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ContactNo.OnIdleState = stateProperties36;
            this.txt_ContactNo.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ContactNo.PasswordChar = '\0';
            this.txt_ContactNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ContactNo.PlaceholderText = "Eg-011 XXX XXXX";
            this.txt_ContactNo.ReadOnly = false;
            this.txt_ContactNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ContactNo.SelectedText = "";
            this.txt_ContactNo.SelectionLength = 0;
            this.txt_ContactNo.SelectionStart = 0;
            this.txt_ContactNo.ShortcutsEnabled = true;
            this.txt_ContactNo.Size = new System.Drawing.Size(263, 35);
            this.txt_ContactNo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ContactNo.TabIndex = 1;
            this.txt_ContactNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ContactNo.TextMarginBottom = 0;
            this.txt_ContactNo.TextMarginLeft = 3;
            this.txt_ContactNo.TextMarginTop = 1;
            this.txt_ContactNo.TextPlaceholder = "Eg-011 XXX XXXX";
            this.txt_ContactNo.UseSystemPasswordChar = false;
            this.txt_ContactNo.WordWrap = true;
            // 
            // txt_ClientAddress
            // 
            this.txt_ClientAddress.AcceptsReturn = false;
            this.txt_ClientAddress.AcceptsTab = false;
            this.txt_ClientAddress.AnimationSpeed = 200;
            this.txt_ClientAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ClientAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ClientAddress.AutoSizeHeight = true;
            this.txt_ClientAddress.BackColor = System.Drawing.Color.Transparent;
            this.txt_ClientAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ClientAddress.BackgroundImage")));
            this.txt_ClientAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ClientAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ClientAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ClientAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ClientAddress.BorderRadius = 1;
            this.txt_ClientAddress.BorderThickness = 1;
            this.txt_ClientAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ClientAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ClientAddress.DefaultText = "";
            this.txt_ClientAddress.FillColor = System.Drawing.Color.White;
            this.txt_ClientAddress.HideSelection = true;
            this.txt_ClientAddress.IconLeft = null;
            this.txt_ClientAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientAddress.IconPadding = 10;
            this.txt_ClientAddress.IconRight = null;
            this.txt_ClientAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientAddress.Lines = new string[0];
            this.txt_ClientAddress.Location = new System.Drawing.Point(144, 196);
            this.txt_ClientAddress.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ClientAddress.MaxLength = 32767;
            this.txt_ClientAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ClientAddress.Modified = false;
            this.txt_ClientAddress.Multiline = false;
            this.txt_ClientAddress.Name = "txt_ClientAddress";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientAddress.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ClientAddress.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientAddress.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientAddress.OnIdleState = stateProperties40;
            this.txt_ClientAddress.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ClientAddress.PasswordChar = '\0';
            this.txt_ClientAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ClientAddress.PlaceholderText = "Home Town Name";
            this.txt_ClientAddress.ReadOnly = false;
            this.txt_ClientAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ClientAddress.SelectedText = "";
            this.txt_ClientAddress.SelectionLength = 0;
            this.txt_ClientAddress.SelectionStart = 0;
            this.txt_ClientAddress.ShortcutsEnabled = true;
            this.txt_ClientAddress.Size = new System.Drawing.Size(270, 35);
            this.txt_ClientAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ClientAddress.TabIndex = 1;
            this.txt_ClientAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ClientAddress.TextMarginBottom = 0;
            this.txt_ClientAddress.TextMarginLeft = 3;
            this.txt_ClientAddress.TextMarginTop = 1;
            this.txt_ClientAddress.TextPlaceholder = "Home Town Name";
            this.txt_ClientAddress.UseSystemPasswordChar = false;
            this.txt_ClientAddress.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(43, 206);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(99, 19);
            this.label6.TabIndex = 0;
            this.label6.Text = "Client Address";
            // 
            // txt_ClientName
            // 
            this.txt_ClientName.AcceptsReturn = false;
            this.txt_ClientName.AcceptsTab = false;
            this.txt_ClientName.AnimationSpeed = 200;
            this.txt_ClientName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ClientName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ClientName.AutoSizeHeight = true;
            this.txt_ClientName.BackColor = System.Drawing.Color.Transparent;
            this.txt_ClientName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ClientName.BackgroundImage")));
            this.txt_ClientName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ClientName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ClientName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ClientName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ClientName.BorderRadius = 1;
            this.txt_ClientName.BorderThickness = 1;
            this.txt_ClientName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ClientName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ClientName.DefaultText = "";
            this.txt_ClientName.FillColor = System.Drawing.Color.White;
            this.txt_ClientName.HideSelection = true;
            this.txt_ClientName.IconLeft = null;
            this.txt_ClientName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientName.IconPadding = 10;
            this.txt_ClientName.IconRight = null;
            this.txt_ClientName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ClientName.Lines = new string[0];
            this.txt_ClientName.Location = new System.Drawing.Point(143, 129);
            this.txt_ClientName.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ClientName.MaxLength = 32767;
            this.txt_ClientName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ClientName.Modified = false;
            this.txt_ClientName.Multiline = false;
            this.txt_ClientName.Name = "txt_ClientName";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientName.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ClientName.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientName.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ClientName.OnIdleState = stateProperties44;
            this.txt_ClientName.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_ClientName.PasswordChar = '\0';
            this.txt_ClientName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ClientName.PlaceholderText = "Mr/Ms";
            this.txt_ClientName.ReadOnly = false;
            this.txt_ClientName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ClientName.SelectedText = "";
            this.txt_ClientName.SelectionLength = 0;
            this.txt_ClientName.SelectionStart = 0;
            this.txt_ClientName.ShortcutsEnabled = true;
            this.txt_ClientName.Size = new System.Drawing.Size(271, 35);
            this.txt_ClientName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ClientName.TabIndex = 1;
            this.txt_ClientName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ClientName.TextMarginBottom = 0;
            this.txt_ClientName.TextMarginLeft = 3;
            this.txt_ClientName.TextMarginTop = 1;
            this.txt_ClientName.TextPlaceholder = "Mr/Ms";
            this.txt_ClientName.UseSystemPasswordChar = false;
            this.txt_ClientName.WordWrap = true;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(40, 136);
            this.label9.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(87, 19);
            this.label9.TabIndex = 0;
            this.label9.Text = "Client Name";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(43, 74);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(45, 19);
            this.label5.TabIndex = 0;
            this.label5.Text = "JobID";
            // 
            // txt_JobID
            // 
            this.txt_JobID.AcceptsReturn = false;
            this.txt_JobID.AcceptsTab = false;
            this.txt_JobID.AnimationSpeed = 200;
            this.txt_JobID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_JobID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_JobID.AutoSizeHeight = true;
            this.txt_JobID.BackColor = System.Drawing.Color.Transparent;
            this.txt_JobID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_JobID.BackgroundImage")));
            this.txt_JobID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_JobID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_JobID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_JobID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_JobID.BorderRadius = 1;
            this.txt_JobID.BorderThickness = 1;
            this.txt_JobID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_JobID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_JobID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_JobID.DefaultText = "";
            this.txt_JobID.FillColor = System.Drawing.Color.White;
            this.txt_JobID.HideSelection = true;
            this.txt_JobID.IconLeft = null;
            this.txt_JobID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_JobID.IconPadding = 10;
            this.txt_JobID.IconRight = null;
            this.txt_JobID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_JobID.Lines = new string[0];
            this.txt_JobID.Location = new System.Drawing.Point(143, 64);
            this.txt_JobID.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_JobID.MaxLength = 32767;
            this.txt_JobID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_JobID.Modified = false;
            this.txt_JobID.Multiline = false;
            this.txt_JobID.Name = "txt_JobID";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_JobID.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_JobID.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_JobID.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_JobID.OnIdleState = stateProperties48;
            this.txt_JobID.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.txt_JobID.PasswordChar = '\0';
            this.txt_JobID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_JobID.PlaceholderText = "Auto Incrementing";
            this.txt_JobID.ReadOnly = true;
            this.txt_JobID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_JobID.SelectedText = "";
            this.txt_JobID.SelectionLength = 0;
            this.txt_JobID.SelectionStart = 0;
            this.txt_JobID.ShortcutsEnabled = true;
            this.txt_JobID.Size = new System.Drawing.Size(271, 35);
            this.txt_JobID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_JobID.TabIndex = 1;
            this.txt_JobID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_JobID.TextMarginBottom = 0;
            this.txt_JobID.TextMarginLeft = 3;
            this.txt_JobID.TextMarginTop = 1;
            this.txt_JobID.TextPlaceholder = "Auto Incrementing";
            this.txt_JobID.UseSystemPasswordChar = false;
            this.txt_JobID.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 17F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(416, 14);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(190, 29);
            this.label1.TabIndex = 0;
            this.label1.Text = "Add New Repair";
            // 
            // lbl_close
            // 
            this.lbl_close.AutoSize = true;
            this.lbl_close.Font = new System.Drawing.Font("Microsoft Sans Serif", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_close.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.lbl_close.Location = new System.Drawing.Point(1010, 3);
            this.lbl_close.Name = "lbl_close";
            this.lbl_close.Size = new System.Drawing.Size(43, 42);
            this.lbl_close.TabIndex = 19;
            this.lbl_close.Text = "X";
            this.lbl_close.Click += new System.EventHandler(this.lbl_close_Click);
            // 
            // ServiceRepair_NewRepair
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(41)))), ((int)(((byte)(53)))));
            this.ClientSize = new System.Drawing.Size(1053, 606);
            this.Controls.Add(this.lbl_close);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "ServiceRepair_NewRepair";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ServiceRepair_NewRepair";
            this.Load += new System.EventHandler(this.ServiceRepair_NewRepair_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dvg_newrepair)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ClientAddress;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ClientName;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txt_JobID;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_TechnicalNote;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ContactNo;
        private Bunifu.UI.WinForms.BunifuTextBox txt_SearchAddnewrepair;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuDataGridView dvg_newrepair;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_clearRepair;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_deleteRepair;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_updateRepair;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_addRepair;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Label lbl_close;
    }
}